---

- name: Install nft tools (deb)
  apt:
    state: present
    pkg:
      - nftables
  when: ansible_os_family == "Debian"

- name: install nft tools (rpm)
  yum:
    state: present
    pkg:
      - nftables
  when: ansible_os_family == "RedHat"

- name: Stop and disable other firewalls
  systemd:
    name: "{{item}}"
    state: stopped
    enabled: no
  with_items:
    - firewalld
  tags:
    - nft-override
  when:
    - nft_disable_firewalld|bool

- name: Enable nft-service
  systemd:
    name: "{{item}}"
    enabled: yes
  with_items:
    - nftables
  tags:
    - nftservice
  when: ansible_os_family == "Debian" or ansible_os_family == "RedHat"

- name: Template nftables.conf
  template:
    src: "{{item.src}}"
    dest: "{{item.dest}}"
    owner: "root"
    group: "root"
    mode: "0700"
    validate: "{{item.validate|default(null)}}"
  with_items:
      - { src: "nftables.conf.j2", dest: "{{nft_main_config}}", backup: "yes", validate: "/usr/sbin/nft -c -f %s" }
  tags:
    - nft
  notify:
    - reload nft service
